### ISSUE TITLE
MatchError: 401 (of class java.lang.Integer)

### ISSUE THREAD

**Issue by francisdb** [waylayio/kairosdb-scala#11]
```
scala.MatchError: 401 (of class java.lang.Integer)
       	at io.waylay.kairosdb.driver.KairosDB$$anonfun$addDataPoints$1.apply(KairosDB.scala:126)
       	at io.waylay.kairosdb.driver.KairosDB$$anonfun$addDataPoints$1.apply(KairosDB.scala:125)
```

**Comment by francisdb** [comment]
Also create an unit / integration test for this case

**Comment by francisdb** [comment]
still fails with exception, maybe also add the url that is checked in the message

```
JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@47b367c; line: 1, column: 2]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2628)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:854)
...
(21 additional frame(s) were not displayed)
```
